<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net9.0</TargetFramework></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../BusinessIQ.Application/BusinessIQ.Application.csproj" />
    <ProjectReference Include="../../../Framework/src/Framework.Infrastructure/Framework.Infrastructure.csproj" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
  </ItemGroup>
</Project>
